CREATE TABLE  book (
ID bigint NOT NULL ,
  BOOK_NUMBER varchar(255) DEFAULT NULL,
  BOOK_PART varchar(255) DEFAULT NULL,
  version integer,
  COPY_NUMBER varchar(255) DEFAULT NULL,
  DECLIMAL_NUMBER varchar(255) DEFAULT NULL,
  INVENTORY_NUMBER varchar(255) DEFAULT NULL,
  LIST_COUNT int DEFAULT NULL,
  NAME varchar(255) DEFAULT NULL,
  BOOK_TYPE_ID bigint DEFAULT NULL,
  CATEGORY_ID bigint DEFAULT NULL,
  ORGANIZATION_ID int DEFAULT NULL, 
  PRIMARY KEY (ID)
  );

CREATE TABLE bookType (
ID bigint NOT NULL ,
  NAME varchar(255) DEFAULT NULL, 
  version integer,
  PRIMARY KEY (ID)
);

CREATE TABLE category (
ID bigint NOT NULL,
  NAME varchar(255) DEFAULT NULL, 
  version integer,
  PRIMARY KEY (ID)
);

CREATE TABLE  delivery (
ID bigint NOT NULL ,
  DELIVERY_DATE date DEFAULT NULL,
  EMPLOYE_ID bigint DEFAULT NULL,
  SURRENDER_DATE date DEFAULT NULL,
  version integer,
  BOOK_ID bigint DEFAULT NULL, 
  PRIMARY KEY (ID)
) ;

CREATE TABLE document (
ID bigint NOT NULL ,
  INCOME_DATE date DEFAULT NULL,
  INCOME_NUMBER varchar(255) DEFAULT NULL,
  MODIFICATION bigint DEFAULT NULL,
  version integer,
  OUTCOME_DATE date DEFAULT NULL,
  OUTCOME_NUMBER varchar(255) DEFAULT NULL,
  BOOK_ID bigint DEFAULT NULL, 
  PRIMARY KEY (ID)
) ;

CREATE TABLE organization (
  ID int NOT NULL ,
  ADDRESS varchar(255) DEFAULT NULL,
  version integer,
  NAME varchar(255) DEFAULT NULL, 
  PRIMARY KEY (ID)
) ;

CREATE TABLE IF NOT EXISTS page (
ID bigint NOT NULL,
  DATA tinyblob,
  NAME varchar(255) DEFAULT NULL,
  version integer,
  DOCUMENT_ID bigint DEFAULT NULL, 
  PRIMARY KEY (ID)
) ;

ALTER TABLE delivery ADD FOREIGN KEY (BOOK_ID) REFERENCES public.book(ID);
ALTER TABLE document ADD FOREIGN KEY (BOOK_ID) REFERENCES book(ID);
ALTER TABLE page ADD FOREIGN KEY (DOCUMENT_ID) REFERENCES document(ID);
ALTER TABLE book ADD FOREIGN KEY (CATEGORY_ID) REFERENCES category (ID);
ALTER TABLE book ADD FOREIGN KEY (ORGANIZATION_ID) REFERENCES organization (ID);
ALTER TABLE book ADD FOREIGN KEY (BOOK_TYPE_ID) REFERENCES bookType (ID);
ALTER TABLE delivery ADD FOREIGN KEY (BOOK_ID) REFERENCES book (ID);
ALTER TABLE document ADD FOREIGN KEY (BOOK_ID) REFERENCES book (ID);
ALTER TABLE page ADD FOREIGN KEY (DOCUMENT_ID) REFERENCES document (ID);